services:
  app:
    build:
      context: .
      target: development
    env_file:
      - ./.env
    ports:
      - 3002:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev